// Master Typst Document generated by Nisse Book Maker
// Title: Quantum Information & Fault-Tolerant Architectures
// Author: Prof. J. Preskill & P. Shor

#import "backend/templates/springer.typ": book, theorem, definition, lemma, proposition, proof, example, remark, chapter-abstract, hbar

#show: book.with(
  title: "Quantum Information & Fault-Tolerant Architectures",
  subtitle: "Algebraic Foundations of Stabilizer Codes, Surface Lattices, and Quantum Supremacy",
  author: "Prof. J. Preskill & P. Shor",
  affiliation: "Institute for Quantum Information & Physics",
  series: "Springer Monographs in Quantum Science",
  discipline: "Quantum Information Science",
  edition: "First Edition",
  dedication: "Dedicated to the pioneers of quantum coherence and algebraic fault-tolerance.",
  preface: [
This textbook offers an axiomatic formulation of quantum error correction, fault-tolerant threshold theorems, and holographic tensor networks.
  ],
  notation_conventions: [
Hilbert space $cal(H)_2^(times n)$; Pauli group $cal(G)_n = {plus.minus 1, plus.minus i} times {I, X, Y, Z}^(times n)$; computational basis $|0 angle, |1 angle$.
  ]
)

= Hilbert Spaces, Density Operators, and Quantum Entanglement

#chapter-abstract[
  We formulate the mathematical geometry of quantum states, von Neumann entropy, partial trace operations, and entanglement monotonicity under LOCC operations.
]


== Postulates of Quantum Mechanics & CPTP Maps

In this section, we examine the analytical foundations of postulates of quantum mechanics & cptp maps.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 1.1 (Postulates of Quantum Mechanics & CPTP Maps)")[
  A mathematical construct corresponding to postulates of quantum mechanics & cptp maps is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ rho = sum_i p_i |psi_i chevron.r chevron.l psi_i| $

$ cal(E)(rho) = sum_k E_k rho E_k^dagger $


#theorem(title: "Theorem 1.1 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for postulates of quantum mechanics & cptp maps admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 1.1 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 1.1")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Quantum Entropy and the Subadditivity Theorem

In this section, we examine the analytical foundations of quantum entropy and the subadditivity theorem.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 1.2 (Quantum Entropy and the Subadditivity Theorem)")[
  A mathematical construct corresponding to quantum entropy and the subadditivity theorem is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ S(rho) = - tr(rho log_2 rho) $

$ S(A B C) + S(B) <= S(A B) + S(B C) $


#theorem(title: "Theorem 1.2 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for quantum entropy and the subadditivity theorem admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 1.2 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 1.2")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Bell Inequalities and Quantum Nonlocality

In this section, we examine the analytical foundations of bell inequalities and quantum nonlocality.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 1.3 (Bell Inequalities and Quantum Nonlocality)")[
  A mathematical construct corresponding to bell inequalities and quantum nonlocality is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ |chevron.l B_("CHSH") chevron.r| <= 2 sqrt(2) $


#theorem(title: "Theorem 1.3 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for bell inequalities and quantum nonlocality admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 1.3 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 1.3")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]



= The Pauli Group and Stabilizer Quantum Error Correction

#chapter-abstract[
  This chapter establishes the algebraic structure of stabilizer codes, symplectic inner products over finite fields $bb(F)_2$, and the Knill-Laflamme error-correction criterion.
]


== The N-Qubit Pauli Group and Symplectic Geometry

In this section, we examine the analytical foundations of the n-qubit pauli group and symplectic geometry.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 2.1 (The N-Qubit Pauli Group and Symplectic Geometry)")[
  A mathematical construct corresponding to the n-qubit pauli group and symplectic geometry is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ cal(S) = chevron.l g_1, g_2, dots, g_(n-k) chevron.r $

$ [g_i, g_j] = 0 $


#theorem(title: "Theorem 2.1 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for the n-qubit pauli group and symplectic geometry admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 2.1 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 2.1")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Knill-Laflamme Conditions for Error Discretization

In this section, we examine the analytical foundations of knill-laflamme conditions for error discretization.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 2.2 (Knill-Laflamme Conditions for Error Discretization)")[
  A mathematical construct corresponding to knill-laflamme conditions for error discretization is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ P E_a^dagger E_b P = C_(a b) P $


#theorem(title: "Theorem 2.2 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for knill-laflamme conditions for error discretization admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 2.2 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 2.2")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== The 7-Qubit Steane Code and CSS Architecture

In this section, we examine the analytical foundations of the 7-qubit steane code and css architecture.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 2.3 (The 7-Qubit Steane Code and CSS Architecture)")[
  A mathematical construct corresponding to the 7-qubit steane code and css architecture is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ |0_L chevron.r = 1/sqrt(8) sum_(c in C^perp) |c chevron.r $


#theorem(title: "Theorem 2.3 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for the 7-qubit steane code and css architecture admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 2.3 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 2.3")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]



= Topological Surface Codes and Anyonic Excitations

#chapter-abstract[
  We analyze the Kitaev toric code on 2D lattices, homology classes of topological defects, and fault-tolerant decoding via minimum-weight perfect matching.
]


== The Kitaev Toric Code Hamiltonian

In this section, we examine the analytical foundations of the kitaev toric code hamiltonian.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 3.1 (The Kitaev Toric Code Hamiltonian)")[
  A mathematical construct corresponding to the kitaev toric code hamiltonian is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ H = - J_e sum_s A_s - J_m sum_p B_p $

$ A_s = product_(i in s) X_i, quad B_p = product_(j in p) Z_j $


#theorem(title: "Theorem 3.1 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for the kitaev toric code hamiltonian admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 3.1 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 3.1")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Braiding Statistics and Anyonic Ground States

In this section, we examine the analytical foundations of braiding statistics and anyonic ground states.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 3.2 (Braiding Statistics and Anyonic Ground States)")[
  A mathematical construct corresponding to braiding statistics and anyonic ground states is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ gamma = ln(sqrt(2)) $


#theorem(title: "Theorem 3.2 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for braiding statistics and anyonic ground states admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 3.2 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 3.2")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Threshold Theorems and MWPM Syndrome Decoding

In this section, we examine the analytical foundations of threshold theorems and mwpm syndrome decoding.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 3.3 (Threshold Theorems and MWPM Syndrome Decoding)")[
  A mathematical construct corresponding to threshold theorems and mwpm syndrome decoding is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ p_("th") approx 10.9% $


#theorem(title: "Theorem 3.3 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for threshold theorems and mwpm syndrome decoding admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 3.3 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 3.3")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]



= Fault-Tolerant Gates and Magic State Distillation

#chapter-abstract[
  We prove the Eastin-Knill theorem prohibiting universal transversal gate sets and construct magic state distillation protocols for universal quantum computation.
]


== The Eastin-Knill No-Go Theorem

In this section, we examine the analytical foundations of the eastin-knill no-go theorem.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 4.1 (The Eastin-Knill No-Go Theorem)")[
  A mathematical construct corresponding to the eastin-knill no-go theorem is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ U_L in cal(C)_k $


#theorem(title: "Theorem 4.1 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for the eastin-knill no-go theorem admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 4.1 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 4.1")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Bravyi-Kitaev Magic State Distillation

In this section, we examine the analytical foundations of bravyi-kitaev magic state distillation.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 4.2 (Bravyi-Kitaev Magic State Distillation)")[
  A mathematical construct corresponding to bravyi-kitaev magic state distillation is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ |T chevron.r = cos(pi/8)|0 chevron.r + sin(pi/8)|1 chevron.r $

$ epsilon_("out") = 35 epsilon_("in")^3 $


#theorem(title: "Theorem 4.2 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for bravyi-kitaev magic state distillation admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 4.2 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 4.2")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Lattice Surgery and Fault-Tolerant Compilers

In this section, we examine the analytical foundations of lattice surgery and fault-tolerant compilers.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 4.3 (Lattice Surgery and Fault-Tolerant Compilers)")[
  A mathematical construct corresponding to lattice surgery and fault-tolerant compilers is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ N_("phys") = cal(O)(d^2 N_("log")) $


#theorem(title: "Theorem 4.3 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for lattice surgery and fault-tolerant compilers admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 4.3 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 4.3")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]



= References and Bibliography

#line(length: 100%, stroke: 0.5pt + rgb("#cbd5e1"))
#v(1em)

1. Hawking, S. W., & Ellis, G. F. R. (1973). *The Large Scale Structure of Space-Time*. Cambridge University Press.

2. Misner, C. W., Thorne, K. S., & Wheeler, J. A. (1973). *Gravitation*. W. H. Freeman and Company.

3. Wald, R. M. (1984). *General Relativity*. University of Chicago Press.

4. Carroll, S. M. (2004). *Spacetime and Geometry: An Introduction to General Relativity*. Addison-Wesley.

5. Nielsen, M. A., & Chuang, I. L. (2010). *Quantum Computation and Quantum Information*. Cambridge University Press.

6. Kitaev, A. Y. (2003). *Fault-tolerant quantum computation by anyons*. Annals of Physics, 303(1), 2-30.

7. Goodfellow, I., Bengio, Y., & Courville, A. (2016). *Deep Learning*. MIT Press.

8. Bronstein, M. M., et al. (2021). *Geometric Deep Learning: Grids, Groups, Graphs, Geodesics, and Gauges*. arXiv:2104.13478.
