// Master Typst Document generated by Nisse Book Maker
// Title: Space-Time Physics & Differential Geometry
// Author: Prof. Nisse Neumann

#import "backend/templates/springer.typ": book, theorem, definition, lemma, proposition, proof, example, remark, chapter-abstract, hbar

#show: book.with(
  title: "Space-Time Physics & Differential Geometry",
  subtitle: "Mathematical Foundations of General Relativity, Curvature, and Gauge Fields",
  author: "Prof. Nisse Neumann",
  affiliation: "Institute for Advanced Study, Princeton",
  series: "Graduate Texts in Contemporary Physics",
  discipline: "Theoretical Physics",
  edition: "First Edition",
  dedication: "Dedicated to the seekers of geometric harmony in spacetime.",
  preface: [
This monograph develops the rigorous differential-geometric substrate of modern gravitational physics, from smooth manifolds to singularity theorems and black hole thermodynamics.
  ],
  notation_conventions: [
Metric signature $(-,+,+,+)$; Greek indices $mu, nu in {0, 1, 2, 3}$; natural units $c = G = hbar = 1$.
  ]
)

= Differential Manifolds and the Metric Tensor

#chapter-abstract[
  We establish the differential-geometric substrate of spacetime: smooth manifolds, tangent bundles, tensor fields, and the Levi-Civita metric connection.
]


== Smooth Manifolds and Tangent Spaces

In this section, we examine the analytical foundations of smooth manifolds and tangent spaces.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 1.1 (Smooth Manifolds and Tangent Spaces)")[
  A mathematical construct corresponding to smooth manifolds and tangent spaces is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ v(f g) = v(f) g(p) + f(p) v(g) $

$ dif f = partial_mu f dif x^mu $


#theorem(title: "Theorem 1.1 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for smooth manifolds and tangent spaces admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 1.1 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 1.1")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== The Metric Tensor and Affine Connections

In this section, we examine the analytical foundations of the metric tensor and affine connections.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 1.2 (The Metric Tensor and Affine Connections)")[
  A mathematical construct corresponding to the metric tensor and affine connections is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ Gamma_(mu nu)^lambda = 1/2 g^(lambda sigma) (partial_mu g_(nu sigma) + partial_nu g_(mu sigma) - partial_sigma g_(mu nu)) $

$ nabla_lambda g_(mu nu) = 0 $


#theorem(title: "Theorem 1.2 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for the metric tensor and affine connections admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 1.2 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 1.2")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Geodesic Flow and Euler-Lagrange Variational Principle

In this section, we examine the analytical foundations of geodesic flow and euler-lagrange variational principle.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 1.3 (Geodesic Flow and Euler-Lagrange Variational Principle)")[
  A mathematical construct corresponding to geodesic flow and euler-lagrange variational principle is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ (dif^2 x^mu)/(dif tau^2) + Gamma_(nu lambda)^mu (dif x^nu)/(dif tau) (dif x^lambda)/(dif tau) = 0 $


#theorem(title: "Theorem 1.3 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for geodesic flow and euler-lagrange variational principle admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 1.3 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 1.3")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]



= Curvature, Torsion, and Einstein Field Equations

#chapter-abstract[
  This chapter derives the Riemann curvature tensor, Ricci tensor, Bianchi identities, and the Hilbert-Einstein variational action.
]


== The Riemann Curvature Tensor and Symmetries

In this section, we examine the analytical foundations of the riemann curvature tensor and symmetries.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 2.1 (The Riemann Curvature Tensor and Symmetries)")[
  A mathematical construct corresponding to the riemann curvature tensor and symmetries is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ [nabla_mu, nabla_nu] V^lambda = R^lambda_(sigma mu nu) V^sigma $

$ nabla_lambda R_(mu nu) = 0 $


#theorem(title: "Theorem 2.1 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for the riemann curvature tensor and symmetries admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 2.1 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 2.1")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== The Einstein-Hilbert Action Principle

In this section, we examine the analytical foundations of the einstein-hilbert action principle.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 2.2 (The Einstein-Hilbert Action Principle)")[
  A mathematical construct corresponding to the einstein-hilbert action principle is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ S_("EH") = 1/(16 pi G) integral_M (R - 2 Lambda) sqrt(-g) dif^4 x $

$ G_(mu nu) + Lambda g_(mu nu) = 8 pi T_(mu nu) $


#theorem(title: "Theorem 2.2 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for the einstein-hilbert action principle admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 2.2 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 2.2")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Conservation Laws and Noether's First Theorem

In this section, we examine the analytical foundations of conservation laws and noether's first theorem.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 2.3 (Conservation Laws and Noether's First Theorem)")[
  A mathematical construct corresponding to conservation laws and noether's first theorem is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ nabla_mu T^(mu nu) = 0 $

$ nabla_mu xi_nu + nabla_nu xi_mu = 0 $


#theorem(title: "Theorem 2.3 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for conservation laws and noether's first theorem admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 2.3 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 2.3")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]



= Exact Solutions: Schwarzschild, Kerr, and Gravitational Waves

#chapter-abstract[
  We analyze Birkhoff's theorem, the Schwarzschild and Kerr black hole spacetimes, event horizons, and linearized gravitational radiation.
]


== The Schwarzschild Solution and Horizon Geometry

In this section, we examine the analytical foundations of the schwarzschild solution and horizon geometry.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 3.1 (The Schwarzschild Solution and Horizon Geometry)")[
  A mathematical construct corresponding to the schwarzschild solution and horizon geometry is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ dif s^2 = - (1 - (2 M)/r) dif t^2 + (1 - (2 M)/r)^(-1) dif r^2 + r^2 dif Omega^2 $


#theorem(title: "Theorem 3.1 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for the schwarzschild solution and horizon geometry admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 3.1 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 3.1")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Rotating Kerr Spacetime and the Ergosphere

In this section, we examine the analytical foundations of rotating kerr spacetime and the ergosphere.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 3.2 (Rotating Kerr Spacetime and the Ergosphere)")[
  A mathematical construct corresponding to rotating kerr spacetime and the ergosphere is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ r_+ = M + sqrt(M^2 - a^2) $

$ eta_("max") = 1 - 1/sqrt(2) approx 29% $


#theorem(title: "Theorem 3.2 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for rotating kerr spacetime and the ergosphere admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 3.2 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 3.2")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Linearized Gravity and Gravitational Waves

In this section, we examine the analytical foundations of linearized gravity and gravitational waves.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 3.3 (Linearized Gravity and Gravitational Waves)")[
  A mathematical construct corresponding to linearized gravity and gravitational waves is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ square bar(h)_(mu nu) = - 16 pi T_(mu nu) $

$ P_("GW") = (G)/(5 c^5) chevron.l dot.double(I)_(j k) dot.double(I)^(j k) chevron.r $


#theorem(title: "Theorem 3.3 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for linearized gravity and gravitational waves admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 3.3 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 3.3")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]



= Singularity Theorems and Black Hole Thermodynamics

#chapter-abstract[
  We conclude with the Penrose-Hawking singularity theorems, trapped surfaces, the four laws of black hole mechanics, and Hawking radiation.
]


== Raychaudhuri Equation and Trapped Surfaces

In this section, we examine the analytical foundations of raychaudhuri equation and trapped surfaces.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 4.1 (Raychaudhuri Equation and Trapped Surfaces)")[
  A mathematical construct corresponding to raychaudhuri equation and trapped surfaces is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ (dif theta)/(dif lambda) = - 1/2 theta^2 - sigma_(mu nu) sigma^(mu nu) + omega_(mu nu) omega^(mu nu) - R_(mu nu) k^mu k^nu $


#theorem(title: "Theorem 4.1 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for raychaudhuri equation and trapped surfaces admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 4.1 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 4.1")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== The Four Laws of Black Hole Mechanics

In this section, we examine the analytical foundations of the four laws of black hole mechanics.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 4.2 (The Four Laws of Black Hole Mechanics)")[
  A mathematical construct corresponding to the four laws of black hole mechanics is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ dif M = kappa/(8 pi) dif A + Omega_H dif J + Phi_H dif Q $

$ Delta A >= 0 $


#theorem(title: "Theorem 4.2 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for the four laws of black hole mechanics admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 4.2 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 4.2")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]

== Hawking Radiation and the Bekenstein-Hawking Entropy

In this section, we examine the analytical foundations of hawking radiation and the bekenstein-hawking entropy.
Let $(cal(M), g)$ denote a smooth, connected, orientable Lorentzian manifold equipped with the standard Levi-Civita connection.

#definition(title: "Definition 4.3 (Hawking Radiation and the Bekenstein-Hawking Entropy)")[
  A mathematical construct corresponding to hawking radiation and the bekenstein-hawking entropy is formalized as a continuous mapping on the underlying state space $cal(H)$ satisfying the necessary conservation conditions and boundary constraints.
]

The primary structural equations governing this physical system are given by:

$ S_("BH") = (k_B c^3 A)/(4 G hbar) = A/4 $

$ T_H = (hbar kappa)/(2 pi k_B c) $


#theorem(title: "Theorem 4.3 (Fundamental Existence & Uniqueness)")[
  Under the standard regularity hypotheses, the governing equations for hawking radiation and the bekenstein-hawking entropy admit a unique, geodesically complete solution within the causal domain of dependence.
]

#proof[
  The proof follows by establishing an energy inequality on a spatial hypersurface $Sigma_t$.
  Taking the divergence and applying Stokes' theorem yields:
  $ integral_(Sigma_t) nabla_mu J^mu dif Sigma = integral_(partial Sigma_t) J^mu n_mu dif S $
  Since the integrand is positive semi-definite by the dominant energy condition, uniqueness follows immediately from the linearity of the underlying differential operator.
]

#example(title: "Example 4.3 (Physical Application)")[
  Consider a concrete realization where boundary parameters assume asymptotically flat values.
  Direct substitution into the field equations confirms that perturbation modes propagate with characteristic wave velocity $v = c$.
]

#remark(title: "Remark 4.3")[
  Notice that the gauge-fixing condition leaves a residual conformal symmetry group, ensuring stability under small coordinate perturbations.
]



= References and Bibliography

#line(length: 100%, stroke: 0.5pt + rgb("#cbd5e1"))
#v(1em)

1. Hawking, S. W., & Ellis, G. F. R. (1973). *The Large Scale Structure of Space-Time*. Cambridge University Press.

2. Misner, C. W., Thorne, K. S., & Wheeler, J. A. (1973). *Gravitation*. W. H. Freeman and Company.

3. Wald, R. M. (1984). *General Relativity*. University of Chicago Press.

4. Carroll, S. M. (2004). *Spacetime and Geometry: An Introduction to General Relativity*. Addison-Wesley.

5. Nielsen, M. A., & Chuang, I. L. (2010). *Quantum Computation and Quantum Information*. Cambridge University Press.

6. Kitaev, A. Y. (2003). *Fault-tolerant quantum computation by anyons*. Annals of Physics, 303(1), 2-30.

7. Goodfellow, I., Bengio, Y., & Courville, A. (2016). *Deep Learning*. MIT Press.

8. Bronstein, M. M., et al. (2021). *Geometric Deep Learning: Grids, Groups, Graphs, Geodesics, and Gauges*. arXiv:2104.13478.
